version: 2

sources:
  - name: raw
    database: casestudy
    schema: raw
    tables:
      - name: customers
        description: "customers"
      - name: accounts
        description: "accounts"
      - name: fx_rates
        description: "fx_rates"
      - name: loans
        description: "loans"
      - name: transactions
        description: "transactions"